pool:
  vmImage: ubuntu-22.04

trigger:
  - main

steps:
 -task: Maven@4
      inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'


