pool: soma

trigger: none

steps:
- task: Maven@2
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'path'
    mavenDirectory: '/usr/share/maven'
    mavenAuthenticateFeed: false
    sonarQubeRunAnalysis: false
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: './Dockerfile'
    tags: 'spc-azdev'
    
