pool:
 python

trigger:
  - main

steps:
 -task: Maven@4
       mavenPomFile: 'pom.xml'
      goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'